services:
  app:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    image: php:8.4-fpm
    container_name: "${APP_NAME}_php"
    restart: always
    tty: true
    ports:
      - "9000:9000"
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini

  web_server:
    image: nginx:1.27.3-alpine
    container_name: "${APP_NAME}_nginx"
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/

  database:
    image: postgres:17
    container_name: "${APP_NAME}_postgres"
    restart: always
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DB_DATABASE}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}

  redis_cache:
    image: redis:7.4.1
    container_name: "${APP_NAME}_redis"
    restart: always
    ports:
      - "6379:6379"

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
    driver: local
